# Generated by Django 4.2.19 on 2025-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('floor', models.IntegerField(default=0)),
                ('type_room', models.CharField(blank=True, max_length=50, null=True)),
                ('num_room', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('isactive', models.IntegerField(default=0)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
